server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@eureka-service:8090/eureka/
  instance:
    instance-id: limit-service-instance
spring:
  application:
    name: limit-service
  cloud:
    config:
      uri: http://localhost:8088
      discovery:
        enabled: true
      name: config-service
min: 
  value: 1
max: 
  value: 10000
