server:
  port: 8081
eureka:
  client:
    serviceUrl:
      defaultZone: http://user:user@localhost:8090/eureka/
  instance:
    instance-id: limit-service-instance
spring:
  application:
    name: limit-service
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8088
      discovery:
        enabled: true
      name: config-service
